version: "3.8"

services:

  inheriting_local_or_pipeline:
    image: envtestimage
    ports:
      - 3333:3333
    environment:
      - USER=$USER
      - LASTNAME=$LASTNAME

  inheriting_dotenv:
    image: envtestimage
    ports:
      - 3334:3334
    env_file:
      - ./.env

  explicitly_set:
    image: envtestimage
    ports:
      - 3335:3335
    environment:
      - USER=MyNameisSetExplicitly
      - LASTNAME=SecondNameExplicit